controllers/tmf-apis/catalog.js, controllers/tmf-apis/ordering.js, controllers/tmf.js, lib/httpClient.js, lib/store.js, lib/tmfUtils.js, test/controllers/tmf-apis/catalog.js, test/controllers/tmf-apis/ordering.js, test/controllers/tmf.js, test/lib/httpClient.js, test/lib/store.js, test/lib/tmfUtils.js, test/utils.js
- Validates user permission for creating product orders
- Includes in a X-Redirection-URL header  the URL created by the charging backend that must be used to access PayPal and authorize the payment
=> Support for including PayPal redirection URL

config.js.template, controllers/shoppingCart.js, controllers/tmf-apis/ordering.js, db/schemas/cartItem.js, lib/tmfUtils.js, package.json, public/resources/core/css/default-theme.css, public/resources/core/js/app.config.js, public/resources/core/js/controllers/flash-message.controller.js, public/resources/core/js/controllers/order.controller.js, public/resources/core/js/controllers/purchase-options.controller.js, public/resources/core/js/controllers/user.controller.js, public/resources/core/js/services/shopping-cart.service.js, server.js, test/controllers/shoppingCart.js, test/lib/tmfUtils.js, views/app.jade, views/base.jade, views/partials/shopping-cart/create.jade
Shopping cart is stored in the backend so users can get it at any time even if they reload the page or access the portal from another browser. Additionally, the server can be restarted and users won't loose their carts
=> Persistent Shopping cart

lib/utils.js, public/resources/core/css/default-theme.css, public/resources/core/js/app.filters.js, public/resources/core/js/controllers/product-category.controller.js, public/resources/core/js/controllers/product-offering.controller.js, public/resources/core/js/services/product-category.service.js, public/resources/core/js/services/product-offering.service.js, server.js, views/base.jade, views/partials/admin/product-category/create-form-finish.jade, views/partials/admin/product-category/create-form.jade, views/partials/admin/product-category/search.jade, views/partials/admin/product-category/update.jade, views/partials/offering/detail-content.jade, views/partials/offering/search.jade, views/partials/product-category.search.jade, views/partials/stock/product-catalogue/update-offering.jade, views/partials/stock/product-offering/create-form-categories.jade, views/partials/stock/product-offering/create-form-finish.jade, views/partials/stock/product-offering/update-category.jade
This pull-request closes #43 .
=> Improve the handle of categories

public/resources/core/css/default-theme.css, public/resources/core/js/controllers/product-offering.controller.js, views/partials/offering/detail-about.jade, views/partials/stock/product-offering/create-form-finish.jade, views/partials/stock/product-offering/create-form.jade, views/partials/stock/product-offering/update-form.jade
=> Add list of places to product offerings

views/partials/stock/product-offering/update-form.jade
=> Remove minlength validator in field name from offering update form

public/resources/core/js/controllers/product.controller.js, public/resources/core/js/services/product-specification.service.js
=> Fix the product spec. assets

views/partials/shopping-cart/create.jade
=> Fix the biilingAccount search view to handle errors

views/partials/stock/product-offering/create-form-priceplan.jade
=> Fix to get back to price plan step from following steps

public/resources/core/css/default-theme.css, public/resources/core/js/app.directives.js, public/resources/core/js/controllers/product-specification.relationship.controller.js, public/resources/core/js/controllers/product.controller.js, public/resources/core/js/routes/offering.routes.js, public/resources/core/js/routes/stock.product.routes.js, public/resources/core/js/services/product-offering.service.js, public/resources/core/js/services/product-specification.service.js, server.js, views/base.jade, views/partials/offering/detail-content.jade, views/partials/offering/detail-relationship.jade, views/partials/stock/product/create-form-finish.jade, views/partials/stock/product/create-relationship.jade, views/partials/stock/product/directives/relationship-create-form.jade, views/partials/stock/product/directives/relationship-delete-form.jade, views/partials/stock/product/update-relationship.jade, views/partials/stock/product/update.jade
=> Support for product spec. relationships

public/resources/core/js/app.directives.js, public/resources/core/js/services/product-offering.service.js
=> Use Number to parse integers

views/partials/settings/general/update-profile.jade, views/partials/stock/product-catalogue/update-form.jade, views/partials/stock/product-offering/update-form.jade, views/partials/stock/product/create-form-characteristic-form.jade, views/partials/stock/product/update-form.jade
=> Remove max-length validator

views/partials/inventory/product-order/search-grid.jade
=> Allow sellers to see product order details

public/resources/core/js/app.config.js, public/resources/core/js/controllers/billing-account.controller.js, public/resources/core/js/controllers/customer.controller.js, public/resources/core/js/controllers/party.contact-medium.controller.js, public/resources/core/js/controllers/party.individual.controller.js, public/resources/core/js/controllers/product-catalogue.controller.js, public/resources/core/js/controllers/product-category.controller.js, public/resources/core/js/controllers/product-offering.controller.js, public/resources/core/js/controllers/product-specification.relationship.controller.js, public/resources/core/js/controllers/product.controller.js, public/resources/core/js/services/customer.service.js, views/partials/admin/product-category/create-form-finish.jade, views/partials/admin/product-category/update-form.jade, views/partials/admin/product-category/update.jade, views/partials/settings/contact/update-business-address.jade, views/partials/settings/contact/update-shipping-address.jade, views/partials/settings/general/update-profile.jade, views/partials/stock/product-catalogue/create-form-finish.jade, views/partials/stock/product-catalogue/update-form.jade, views/partials/stock/product-catalogue/update.jade, views/partials/stock/product-offering/create-form-finish.jade, views/partials/stock/product-offering/directives/priceplan-table.jade, views/partials/stock/product-offering/update-form.jade, views/partials/stock/product-offering/update-priceplan.jade, views/partials/stock/product-offering/update.jade, views/partials/stock/product/create-form-finish.jade, views/partials/stock/product/directives/relationship-create-form.jade, views/partials/stock/product/directives/relationship-delete-form.jade, views/partials/stock/product/update-form.jade, views/partials/stock/product/update.jade
=> Use promise status in forms

public/resources/core/js/controllers/product-catalogue.controller.js, public/resources/core/js/controllers/product-category.controller.js, public/resources/core/js/controllers/product-offering.controller.js, public/resources/core/js/controllers/product.controller.js, public/resources/core/js/services/utils.service.js, views/partials/admin/product-category/search.jade, views/partials/stock/product-catalogue/search.jade, views/partials/stock/product-offering/create-form-catalogue.jade, views/partials/stock/product-offering/create-form-categories.jade, views/partials/stock/product-offering/create-form-product.jade, views/partials/stock/product-offering/create.jade, views/partials/stock/product/create-form-bundle.jade, views/partials/stock/product/search.jade
=> OfferingCreateForm: error handling

controllers/tmf-apis/ordering.js, package.json, public/resources/core/css/default-theme.css, public/resources/core/js/controllers/product-order.controller.js, public/resources/core/js/routes/inventory.product-order.routes.js, public/resources/core/js/services/product-order.service.js, test/controllers/tmf-apis/ordering.js, views/base.jade, views/partials/inventory/product-order/detail-note.jade, views/partials/inventory/product-order/detail-product.jade, views/partials/inventory/product-order/detail.jade, views/partials/inventory/product-order/search-grid.jade, views/partials/shopping-cart/create.jade
=> Improve product order detail view

.gitignore, controllers/tmf-apis/catalog.js, fill_indexes.js, lib/indexes.js, package.json, test/controllers/tmf-apis/catalog.js, test/lib/indexes.js
- Library to work with the index easily
- Middleware to save on POST/PUT/PATCH and change apiUrl on GET
- Script to fill the index with all the data in the database
- Tests for library and middlewares
=> Add indexes of catalogs, products and offers and allow for search in get queries.

controllers/tmf-apis/catalog.js, controllers/tmf-apis/inventory.js, controllers/tmf-apis/ordering.js, fill_indexes.js, lib/indexes.js, lib/inventory_subscription.js, package.json, server.js, test/controllers/tmf-apis/inventory.js, test/controllers/tmf-apis/ordering.js, test/controllers/tmf.js, test/lib/indexes.js, test/lib/inventory_subscription.js
Add inventory and ordering index.
Create inventory subscription to save index and test it.
Test inventory and ordering index.
Fix and improve catalog and tmf tests.
=> Inventory, ordering index and minor fixes.

controllers/tmf-apis/catalog.js, controllers/tmf-apis/inventory.js, controllers/tmf-apis/ordering.js, lib/indexes.js, test/controllers/tmf-apis/catalog.js, test/controllers/tmf-apis/inventory.js, test/controllers/tmf-apis/ordering.js, test/lib/indexes.js
White list of other-params in index middleware, and if no index results the result URL don't have ids
=> Fix indexes

db/schemas/tokenService.js, server.js
Allow different app token, synched with local app token information and cache data only last one hour.
=> Allow different app tokens, but using local app information.

controllers/tmf-apis/catalog.js, lib/indexes.js, server.js, test/controllers/tmf-apis/catalog.js, test/controllers/tmf-apis/inventory.js, test/controllers/tmf-apis/ordering.js, test/lib/indexes.js
=> Save in index categories of offers and allow search by category id and name

public/resources/core/js/controllers/pager.controller.js, public/resources/core/js/controllers/product-catalogue.controller.js, views/partials/offering/sidebar.jade
Sorry about the debug console log!
=> Unnecessary things removed

lib/auth.js, lib/utils.js, public/resources/core/js/app.config.js, public/resources/core/js/controllers/inventory-product.controller.js, public/resources/core/js/controllers/product-catalogue.controller.js, public/resources/core/js/controllers/product-offering.controller.js, public/resources/core/js/controllers/product-order.controller.js, public/resources/core/js/controllers/product.controller.js, public/resources/core/js/controllers/sharing-reports.controller.js, public/resources/core/js/controllers/transactions.controller.js, public/resources/core/js/controllers/user.controller.js, public/resources/core/js/services/inventory-product.service.js
Missing some roles control and fix some minor bugs
=> WiP/ full support to organization/individual switching actions. 

docker/Dockerfile
This PR adds a healthcheck command in the dockerfile.
=> Add healthcheck command

config.js, controllers/tmf-apis/party.js, lib/auth.js, lib/strategies/aimarket.js, package.json, public/resources/core/js/controllers/party.individual.controller.js, server.js, test/controllers/tmf-apis/party.js, test/lib/strategies/aimarket.js, test/lib/strategies/fiware.js, test/utils.js, views/base.jade, views/partials/settings/general/update-profile.jade
* New strategy for AI Market project supporting user extra fields
* Support for disabling editing party info forms
* Support for Party characteristics
* Update party object with IDM info on login
=> AI Market strategy and party extra data

lib/auth.js, lib/strategies/keycloak.js
Support for API calls from an external system when the access token is provided
=> Support API calls

lib/tmfUtils.js, test/lib/tmfUtils.js
If relatedParty doesn't have the expected atributes, it could be crashed and instantly terminated
=> party role critical bug fixed
